### ISSUE TITLE
credentials.toml error with v0.2.1 WINDOWS

### ISSUE THREAD

**Issue by tmblrxaos** [subnomo/tumblr-likes#1]
Just downloaded the latest version of tumblr-likes and followed instructions but am receiving this error:

> There was an error fetching your likes. Is there a mistake in credentials.toml?

_Is there a workaround?_

**Comment by rsr-at-mindtwin** [comment]
Likes must be set to public on the blog.

**Comment by subnomo** [comment]
Are you passing the correct API key and blog name? Also, like @rsr-at-mindtwin said, likes must be public.

**Comment by tmblrxaos** [comment]
Thanks @rsr-at-mindtwin, setting Tumblr Likes to be public fixed the issue and it is now working.
