### ISSUE TITLE
Can't install on OSX 10.14.1

### ISSUE THREAD

**Issue by vorg** [subnomo/tumblr-likes#2]
I'm getting the following error (among others that follow) when trying to install on osx via `cargo install tumblr-likes`

```sh
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
```

From googling it seems to be `cargo` problem but not sure how to fix it.

**Comment by subnomo** [comment]
Do you have Homebrew installed? Seems like this is an issue with Homebrew doing some weird symlink stuff.

Try this during install:

```
$ DYLD_LIBRARY_PATH=/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/ cargo install tumblr-likes
```

Alternatively, you could do the things listed [here](https://github.com/sgrif/pq-sys/issues/1#issuecomment-231578202), but that might break things for whatever Homebrew packages are depending on `libjpeg`.

**Comment by vorg** [comment]
Setting DYLIB didn't work. Following [your link](https://github.com/sgrif/pq-sys/issues/1#issuecomment-231578202]) (not recommended as it can break other things) worked once I've added libGIF.
