### ISSUE TITLE
Command Prompt Closes Immediately

### ISSUE THREAD

**Issue by Wyatt-Plaga** [subnomo/tumblr-likes#5]
As soon as I launch the executable, the command prompt opens and then immediately closes (almost too fast to see.) Am I doing something wrong?

**Comment by subnomo** [comment]
tumblr-likes is a command-line tool, so it's meant to be used from within the command prompt. If you're looking for something with an interface, check out [TumblThree](https://github.com/johanneszab/TumblThree/).
